# K-Means Clustering with scikit-learn

We are going to use the implementation for k-means from scikit-learn, see [here](http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans.fit) for a documentation. 

In [4]:
from sklearn.cluster import KMeans

When using k-means from scikit-learn, we recommend you that your data be stored as a numpy array. Create it or convert your data into a numpy array as follows.

In [1]:
import numpy as np

# create a numpy array
X = np.array([[1, 2], [1, 4], [1, 0],[4, 2], [4, 4], [4, 0]])

# convert a list to a numpy array
a=[]
for i in range(0,10):
    p=[i,2*i]
    a.append(p)

Y=np.array(a, dtype='float64')


In [2]:
Y

array([[ 0.,  0.],
       [ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.]])

The following execute the k-means algorithm on the points in X. Make sure you understand the parameters see [here](http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans.fit)

In [5]:
kmeans = KMeans(init='random', n_clusters=2, max_iter=10000, n_init=100).fit(X)

C:\Users\19928\.conda\envs\dm\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


The following code shows for each data points its cluster (0 or 1)

In [6]:
kmeans.labels_

array([0, 0, 0, 1, 1, 1], dtype=int32)

The following code computes the clusters for the points [0,0] and [4,4]. In this case, [0,0] is placed in cluster labeled 0 and [4,4] in the cluster labeled 1.

In [16]:
kmeans.predict([[0, 0], [4, 4]])

array([1, 0], dtype=int32)

The following code shows the centroids (in this case called centers ) of the two clusters.

In [15]:
kmeans.cluster_centers_

array([[4., 2.],
       [1., 2.]])

In [7]:
from sklearn.metrics import silhouette_score

# 获取聚类标签
labels = kmeans.labels_
silhouette_avg = silhouette_score(X, labels)
print(f'Silhouette Score: {silhouette_avg:.3f}')


Silhouette Score: 0.287
